CRUD
principlebrothers/to-do-list-app pull request #1
Opened 2022-11-09 09:04 UTC by principlebrothers

## Complete milestone 1
In this milestone, I implemented the functionalities below
- [x] Add Task
- [x] Delete Task
- [x] Update Task
- [x] Toggle Task Completion

2022-11-12 14:48 UTC, TracK92 requested changes
Hi @principlebrothers, 

This is @TracK92, your code reviewer for this project 😄 
You've done such a great job on your application. You should commend yourself 👏🏽 

![14d82a49c68b30cda311f06cb49d3b71](https://user-images.githubusercontent.com/40690789/201479070-d2ed8c73-5f67-4b56-954d-f5044edcfa98.gif)

## Highlights ✅ 

- [x] Good use of DRY, KISS AND YAGNI rules
- [x] Project works as expected
- [x] Proper implementation of Gitflow
- [x] Meaningful commit messages and descriptive pull requests
- [x] Descriptive README file
- [x] Great project design

## Required Changes ♻️ 

- [ ] Please check the comments under the review to see the suggested changes for your project.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@TracK92] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-12 14:48 UTC, TracK92 commented on src/App.js
> +
- [ ] I encountered `eslint` errors while loading your application. Even though your checks have passed on GitHub, this is an issue that cannot be ignored as it may compromise the `UX`. Therefore, kindly find the bug in your code and fix it to make your project even better.

![todo-review](https://user-images.githubusercontent.com/40690789/201477549-706264ba-6139-4528-b408-199dace624bf.png)

2022-11-12 14:48 UTC, TracK92 commented on src/App.js
> +  const [updateData, setUpdateData] = useState('');
- [ ] While reviewing your application, I noticed that your data is not being saved to localStorage. Kindly save your data to localStorage to ensure that the user does not lose information whenever they leave the site. 

![nolocalstorage](https://user-images.githubusercontent.com/40690789/201477845-3c838af4-2c6d-45ce-b548-ad30a1010d1b.png)

2022-11-12 14:48 UTC, TracK92 commented on README.md
> +- Once the download is complete you will be able to access my project locally .
[OPTIONAL]

- [ ] While you have a very detailed and comprehensive `README` file, I would recommend that you simply certain aspects of it for the benefit of beginners in programming. A good `README` file should be easily understandable even to users without any programming background. For example, to simply the highlighted section, you could provide an optional suggestion that would be easier for users: `git clone <repository_link>`

2022-11-12 14:48 UTC, TracK92 commented on src/App.css
> +}
[OPTIONAL]

- [ ] I noticed that you use only one CSS file (`App.css`) for your entire project. I suggest that you consider using CSS modules for each component because it makes your work more professional as your projects get bigger and more complex. Follow this [LINK](https://css-tricks.com/css-modules-part-1-need/) for more information on CSS modules.

![css modules](https://user-images.githubusercontent.com/40690789/201478386-e182459c-ca34-4042-99ea-71f034637736.png)

2022-11-12 14:48 UTC, TracK92 commented on src/components/ToDo.jsx
> +                <span title='Delete' onClick={(e) => deleteTask(todo.id)}><FontAwesomeIcon icon={faTrashCan} /></span>
[OPTIONAL]

- [ ] I noticed that you write most of your functions inside the components. I suggest that you consider writing functions outside components as it makes them easier to  define, read, and test if the function does not rely on props. Kindly, read this article for more information on [this article](https://medium.com/the-fours/writing-functions-outside-vs-inside-in-react-c9044ea31ee2) for more information on this concept.

2022-11-12 23:58 UTC, principlebrothers commented
Thank you @TracK92  for the review. I will go through and implement the suggestions

2022-11-13 15:06 UTC, principlebrothers commented on src/App.js
> +  const [updateData, setUpdateData] = useState('');
Hello @TracK92 , I am working on the storage on another branch so once I am done, I will merge it.

2022-11-13 15:06 UTC, principlebrothers commented on README.md
> +
Thank you

2022-11-13 15:07 UTC, principlebrothers commented on src/App.css
> +}
Alright

2022-11-13 17:00 UTC, TracK92 approved these changes
# APPROVED 🥇 

### Hi @principlebrothers  👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 🎉 🎉 🎉 🎉 

## Highlights ✅ 

- [x] Great front-end design
- [x] Implementation of `Gitflow`
- [x] The project works as expected
- [x] Effective application of DRY, KISS and YAGNI rules
- [x] No `linter` errors

![image](https://i.pinimg.com/originals/77/0e/b0/770eb057449582c44672b2d2d1cc39b6.gif)

Feel free to contact me on Slack or reply to this comment by tagging me (@TracK92) if something is unclear to you.

Cheers and Happy coding!👏👏👏

2022-11-13 17:08 UTC, principlebrothers commented
I appreciate the time spent to review my work.

2022-11-13 17:08 UTC, merged